### ISSUE TITLE
AWS_PROFILE not forwarded

### ISSUE THREAD

**Issue by andreialecu** [Quobject/aws-cli-js#10]
We generally use `AWS_PROFILE` to switch between profiles, but it seems that the variable isn't forwarded properly so commands fail because awscli can't find proper credentials. Or worse, it may use a different set of credentials than the user expects.

See: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html

`AWS_PROFILE` should be added here:
https://github.com/Quobject/aws-cli-js/blob/master/src/index.ts#L34-L36

**Comment by jrnewton** [comment]
I had the same problem as @andreialecu and have submitted a PR.  Hope that's okay.  :)

**Comment by mattqs** [comment]
https://github.com/Quobject/aws-cli-js/releases/tag/2.1.0
