### ISSUE TITLE
Remove `console.error(message);` on line 60 in aws-cli-js/lib/index.js

### ISSUE THREAD

**Issue by SpinGit** [Quobject/aws-cli-js#11]
Hi,

my issue describes the error message on line 60 in aws-cli-js/lib/index.js. I'm using aws-cli-js `command` function to wrap the AWS CLI. Here i get a ResourceNotFound Exception when i describe a ressource which not exists. Thats okay, but i do get a error message because of `console.error(message);` on line 60.

Can you please remove `console.error(message);`?

Current workaround

`console.error = function() {}`

Thank you.

**Comment by mattqs** [comment]
Done in new release: https://github.com/Quobject/aws-cli-js/releases/tag/2.1.0
