### ISSUE TITLE
docs: set config via cli arguments

### ISSUE THREAD

**Issue by sudo-kaizen** [Quobject/aws-cli-js#13]
Great work here! I think this package will be a solution to the problem I've been trying to solve.

1. Is there any way that one can set these options via a command line argument. For example `aws-cli-js --accessKey XXXX -- secretKey XXXX`?

2. _Request_: Could you please include it in the docs if it exists?

3. Does this package also work for the UNIX as well as the Windows cli if the feature to set the variables from the command line exists?

4. Is the main function of this package to create the config file in the locations described at [Location of the shared config and credentials files
](https://docs.aws.amazon.com/credref/latest/refdocs/file-location.html)

Thanks

**Comment by mattqs** [comment]
I don't understand this issue. 

This library is a wrapper around the call to the aws command line tool, so to make it easier to call the aws command withing javascript. If you don't want to call it withing javascript then this library 'aws-cli-js' is not needed. Just call the original library directly and pass any options you want. No js needed.

If you still want/need javascript, you can write a small nodejs program and use something like https://www.npmjs.com/package/commander to accept any command line arguments you want.
