### ISSUE TITLE
With Callback showing below error

### ISSUE THREAD

**Issue by patelvishal1401** [Quobject/aws-cli-js#15]
I am executing same code which is in example for callback 

aws.command('iam list-users').then(function (data) {
  console.log('data = ', data); 
});

showing below error

error =  error: 'Error: spawn aws ENOENT' stdout = '' stderr = ''

Anyone faced this issue ?

**Comment by mattqs** [comment]
Remember:
```
The aws command line interface must be installed and accessible in the path
```

**Comment by patelvishal1401** [comment]
HI, @mattqs  thanks for responding, 

you mean official aws cli lib ? 

Link : https://github.com/aws/aws-cli 

Thanks in advance.

**Comment by mattqs** [comment]
@patelvishal1401

Yes.

Check by using terminal command `aws --version`.

For me on ubuntu:
```
aws --version
aws-cli/1.18.69 Python/3.8.2 Linux/5.4.72-microsoft-standard-WSL2 botocore/1.16.19
``

**Comment by patelvishal1401** [comment]
@mattqs Yah successfully working. 

Thanks, Closing this issue.
