### ISSUE TITLE
Using space inside parameter

### ISSUE THREAD

**Issue by fnzbj7** [Quobject/aws-cli-js#16]
I tried to upload an image to S3 and set the cache-control to "public, max-age=31536000"
My command was something like this:

> aws.command('s3api put-object --bucketb --key pic.png ' +
> 	'--body f:\\\\pic.png ' +
> 	'--acl public-read --content-type image/png --cache-control "public, max-age=31536000"')

But i got back error with message 

> Unknown options: max-age=31536000"

The documentetion for the aws-cli can be found [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-parameters-quoting-strings.html)!

It says if you want to use space between the parameter, you can use quotes

**Comment by mattqs** [comment]
The reason is again:

[...command.split(' ')] 
introduced by commit
1d0525a#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80

@69

I will fix and publish new release.

**Comment by mattqs** [comment]
Fixed in https://github.com/Quobject/aws-cli-js/releases/tag/2.2.2
