### ISSUE TITLE
Running aws-cli-js inside aws Lambda function

### ISSUE THREAD

**Issue by erezstmn** [Quobject/aws-cli-js#3]
I am trying to run a lambda function with the aws-cli-js as a dependency. 
here is the code:
```
var awsCli = require('aws-cli-js');
var Options = awsCli.Options;
var Aws = awsCli.Aws;

var options = new Options('MY_KEY','MY_SECRET_KEY');
var aws = new Aws(options);
exports.handler = function (event, context, callback) {
    console.log(process.env['PATH']);
    aws.command('SOME_AWS_CLI_COMMAND).then(res => {
        console.log('success')
        context.done(null)
    }, err => {
        console.log(err)
    }).catch(err => {
        console.log(err)
    })
};
```
But I am getting this message when I invoke the function:

> stdout = '' stderr = '/bin/sh: aws: command not found

Now, I am guessing it has to do with lambda env variables but could find a solution to this problem. 
Best,

**Comment by mattqs** [comment]
https://github.com/Quobject/aws-cli-js#step-1-prerequisites
The aws command line interface must be installed and accessible in the path

For ubuntu 16-04 this would be like:
https://www.slashroot.in/how-to-install-and-configure-aws-cli-on-ubuntu-16-04

I don't think you can do this in aws lambda.

You should be able to use:
https://www.npmjs.com/package/aws-sdk

**Comment by kaushalshah98** [comment]
I am facing the same issue.. Have you find any answers. How to execute commands from nodejs?

**Comment by iDVB** [comment]
There appears to be a way if you [load the AWS CLI into the function as a layer](https://bezdelev.com/hacking/aws-cli-inside-lambda-layer-aws-s3-sync/).  There are very great reason to prefer the CLI over the SDK, especially wrt S3 operations like sync and deleting all files.
There is then Python code examples that show how to execute AWS CLI commands from within the lambda.

I wish there was an example of how to do this with NodeJS.

It would be great if this wrapper allowed you to pass in the path to the CLI at instantiation.
It might then just work in the above scenario.

**Comment by mattqs** [comment]
@iDVB I have added cli path option: https://github.com/Quobject/aws-cli-js/releases/tag/2.2.0

**Comment by iDVB** [comment]
Great! That was quick. Thanks @mattqs !

**Comment by Gricardov** [comment]
> @mattqs There appears to be a way if you [load the AWS CLI into the function as a layer](https://bezdelev.com/hacking/aws-cli-inside-lambda-layer-aws-s3-sync/). There are very good reasons to prefer the CLI over the SDK, especially wrt S3 operations like sync and deleting all files. There is then Python code examples that show how to execute AWS CLI commands from within the lambda.
> 
> I wish there was an example of how to do this with NodeJS.
> 
> It would be great if this wrapper allowed you to pass in the path to the CLI at instantiation. It might then just work in the above scenario.

Could you provide a working example please?
