### ISSUE TITLE
SyntaxError: Unexpected token P in JSON at position 27

### ISSUE THREAD

**Issue by ithustle** [Quobject/aws-cli-js#4]
I'm trying to list my objects on my bucket. Check the code:

```
aws_cli.command('s3 ls s3://bucket').then(function (data) {
        console.log(data); 
});
```

On cmd (btw, I'm on windows) its working good but on NodeJS, no.

A little help? :)

**Comment by mattqs** [comment]
The output must be in json format. Try including `--output json`.

https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-output.html#cli-usage-output-format
