### ISSUE TITLE
Upgrade lodash version to 4.17.11 due to vulnerability

### ISSUE THREAD

**Issue by chris-zioutas-cko** [Quobject/aws-cli-js#5]
Lodash 4.17.10 and lower seem to be affected by a moderate vulnerability.
As this is a minor version change it should not have any breaking changes.

It would be great if we can get this upgrade! I can make the PR.

**Comment by mattqs** [comment]
Done in aws-cli-js@2.0.5

**Comment by chris-zioutas-cko** [comment]
Great!
